### PR TITLE
RM-8433 Set max length of ClassWithAllDataTypes.NullableBinaryProperty from 1000000 to 1000

### PR DESCRIPTION
**Pull request by a-ctor**
https://re-motion.atlassian.net/browse/RM-8433

### CODE REVIEW

**Review by MichaelKetting — CHANGES_REQUESTED** [review]
Please update the SetupDB.sql script to mirror this change in the datebase: `varbinary(1000)` instead of `varbinary(max)`.

**Review by MichaelKetting — CHANGES_REQUESTED** [review]
Considering the updated semantics, should the image use "<1kB" instead of "<1 MB" to clearly communicate intent? Plz re-request if that's not a good idea.

Am surprised we don't need to change Image2 as well?

**Comment by a-ctor** [comment]
whoops metric is hard...

**Review by MichaelKetting — APPROVED** [review]
Just for completeness' sake: it's kB with a lower-case "k".

**Pull request merged**
